Repository sonic-net/sonic-sairedis, pull requests merged in 2019-07, with the labels that each got.

#475 Add specific comparison logic for tunnel map
  syncd/syncd_applyview.cpp
  tests/brcm.pl
  tests/brcm/tunnel_map.rec
  vslib/src/sai_vs_switch_BCM56850.cpp
Labels: Enhancement

#478 Reduce the timeout (GET_RESPONSE_TIMEOUT) from 6 minutes to 1 minute.…
  lib/inc/sai_redis.h
Labels: Enhancement

#481 [vslib] add ACL action capabilities support
  meta/sai_meta.cpp
  vslib/src/sai_vs_switch_BCM56850.cpp
  vslib/src/sai_vs_switch_MLNX2700.cpp
Labels: Enhancement

#484 Add specific comparison logic for ACL counter
  syncd/syncd_applyview.cpp
  tests/brcm.pl
  tests/brcm/acl_counter.rec
Labels: Enhancement

#483 Process flex counters requests in separate thread
  syncd/syncd.cpp
Labels: Enhancement

#476 Make sairedis/syncd synchronous
  lib/inc/sai_redis.h
  lib/inc/sairedis.h
  lib/src/sai_redis_generic_create.cpp
  lib/src/sai_redis_generic_get.cpp
  lib/src/sai_redis_generic_remove.cpp
  lib/src/sai_redis_generic_set.cpp
  lib/src/sai_redis_interfacequery.cpp
  lib/src/sai_redis_switch.cpp
  saiplayer/saiplayer.cpp
  syncd/syncd.cpp
  tests/aspell.en.pws
Labels: Enhancement

#487 Fixed conditional operator
  syncd/scripts/syncd_init_common.sh
Labels: Enhancement, Request for 201811 Branch :shipit:

#491 Fix bug: Restore sai log levels from LOGLEVEL_DB after saiDiscover
  syncd/syncd.h
  syncd/syncd_saiswitch.cpp
Labels: Request for 201811 Branch :shipit:

#493 [saisdkdump]: Fix dump generation crash
  saisdkdump/saisdkdump.cpp
Labels: Bug, Request for 201811 Branch :shipit:
