Repository sonic-net/sonic-sairedis, pull requests merged in 2019-02, with the labels that each got.

#416 Add more information on failed map sizes
  syncd/syncd_applyview.cpp
Labels: enhancement

#417 Add support for vlan tagged frames in virtual switch
  vslib/src/sai_vs_hostintf.cpp
Labels: enhancement

#418 Move warm_restart enable/disable config to stateDB WARM_RESTART_ENABL…
  syncd/scripts/syncd_init_common.sh
Labels: Request_for_201811_branch :shipit:

#421 Add more specific logic for ingress ACL and buffer profile
  syncd/syncd_applyview.cpp
Labels: Request_for_201811_branch :shipit:, enhancement

#419 [vslib] add missing port attributes for virtual switch
  tests/aspell.en.pws
  vslib/src/sai_vs_switch_BCM56850.cpp
  vslib/src/sai_vs_switch_MLNX2700.cpp
Labels: Request_for_201811_branch :shipit:

#420 Add support for fdb_event MOVE and check fdb event oids
  meta/sai_meta.cpp
  saiplayer/saiplayer.cpp
  syncd/syncd.cpp
  syncd/syncd.h
  syncd/syncd_notifications.cpp
Labels: enhancement
