Repository sonic-net/sonic-sairedis, pull requests merged in 2019-09, with the labels that each got.

#506 fix found typo in new added syncMode related codes
  lib/src/sai_redis_generic_create.cpp
  lib/src/sai_redis_generic_remove.cpp
  lib/src/sai_redis_generic_set.cpp
Labels: Enhancement

#502 Add extra check for warm boot discovered RIDs
  syncd/syncd_applyview.cpp
  syncd/syncd_hard_reinit.cpp
Labels: Enhancement

#511 Add acl counter match logic based on acl entry field
  syncd/syncd_applyview.cpp
  tests/brcm.pl
  tests/brcm/acl_counter2.rec
Labels: Request for 201811 Branch :shipit:

#514 Fix c_str() in printf for string
  vslib/src/sai_vs_port.cpp
Labels: Bug
