Repository sonic-net/sonic-sairedis, pull requests merged in 2019-11, with the labels that each got.

#529 Enable FastReboot if we have key "FAST_REBOOT|system" in State db
  syncd/scripts/syncd_init_common.sh
Labels: Bug

#531 [vs] Implement indices for debug counters in VS
  vslib/src/sai_vs_debug_counter.cpp
Labels: Enhancement, Request for Virtual Switch :zap:

#533 Add support for remove hostif when using tap device
  vslib/inc/sai_vs_state.h
  vslib/src/sai_vs_hostintf.cpp
  vslib/src/sai_vs_switch.cpp
Labels: Enhancement

#536 [syncd] Fix off-by-one error for attribute enum values query
  syncd/syncd.cpp
Labels: Bug

#535 [vs] Send port status notification when creating hostif interface
  lib/src/sai_redis_interfacequery.cpp
  syncd/syncd.cpp
  vslib/inc/sai_vs_state.h
  vslib/src/sai_vs_hostintf.cpp
Labels: Enhancement

#538 Don't learn fdb entries on LAG when rif based
  vslib/src/sai_vs_hostintf.cpp
Labels: Enhancement
