Repository sonic-net/sonic-sairedis, pull requests merged in 2020-09, with the labels that each got.

#654 Fix Warmboot Issue when upgraded Image SAI return Switch Internal OID not accounted in previous image.
  syncd/SaiSwitch.cpp
  syncd/SaiSwitch.h
Labels: Bug, Request for 201911 Branch

#662 Fix typo at SAI_ATTR_VALUE_TYPE_ACL_FIELD_DATA_UINT32
  meta/saiserialize.cpp
Labels: Bug

#663 [LGTM] Add libzmq5 and libzmq3-dev
  lgtm.yml
Labels: Enhancement
