Repository sonic-net/sonic-sairedis, pull requests merged in 2020-12, with the labels that each got.

#723 [meta] Use memcpy instead of cast to prevent strict-aliasing error
  meta/MetaKeyHasher.cpp
Labels: Enhancement

#726 [syncd] Process all cases fdb flush notification
  syncd/syncd_notifications.cpp
Labels: Enhancement

#721 Code clean
  lib/src/sai_redis_switch.cpp
  meta/Meta.cpp
  meta/saiserialize.cpp
  syncd/AsicView.cpp
  syncd/SaiDiscovery.cpp
  syncd/SaiSwitch.cpp
  syncd/Syncd.cpp
  syncd/ZeroMQSelectableChannel.cpp
  vslib/src/NetMsgRegistrar.cpp
  vslib/src/sai_vs_port.cpp
Labels: Enhancement

#739 [vs] Fail switch create when warm boot requested and no warm boot state
  syncd/Syncd.cpp
  vslib/src/VirtualSwitchSaiInterface.cpp
Labels: Enhancement

#728 Switch Capability support
  vslib/src/SwitchStateBase.cpp
  vslib/src/tests.cpp
Labels: brcm-upstream

#735 [vs] Support flush entry type all on virtual switch
  vslib/src/VirtualSwitchSaiInterfaceFdb.cpp
Labels: Enhancement

#740 [vs] Use meta class instead info when using unittests
  meta/Meta.h
  vslib/src/SaiUnittests.cpp
Labels: Enhancement

#738 [meta] Enable strict cast-align warning
  configure.ac
  meta/MetaKeyHasher.cpp
Labels: Enhancement

#741 Remove Winline warning since it depends on external headers
  configure.ac
Labels: Enhancement

#736 [saidiscovery] Update saidiscovery to use VendorSai object and metadata
  meta/Meta.cpp
  saidiscovery/Makefile.am
  saidiscovery/saidiscovery.cpp
Labels: Enhancement

#729 [syncd] Translate removed RIDs in fdb notification
  syncd/syncd.cpp
  syncd/syncd.h
  syncd/syncd_notifications.cpp
Labels: Enhancement

#744 [vs] Use /sbin/ip absolute path for ip command in MACsecManager
  vslib/src/MACsecManager.cpp
Labels: Enhancement

#742 [syncd] Move syncd classes to syncd namespace
  syncd/PortMap.cpp
  syncd/PortMap.h
  syncd/PortMapParser.cpp
  syncd/PortMapParser.h
  syncd/TimerWatchdog.cpp
  syncd/TimerWatchdog.h
Labels: Enhancement

#734 [syncd] Translate removed RIDs in fdb notification
  syncd/NotificationProcessor.cpp
  syncd/RedisClient.cpp
  syncd/Syncd.cpp
  syncd/VirtualOidTranslator.cpp
  syncd/VirtualOidTranslator.h
Labels: Enhancement

#746 [syncd] Translate depreacated attr enum values to new ones
  meta/saiserialize.cpp
  syncd/ComparisonLogic.cpp
  syncd/SaiAttr.cpp
  syncd/SaiSwitch.cpp
Labels: Enhancement

#749 Configure enable -Wcast-align=strict when supported by compiler
  configure.ac
Labels: Enhancement

#750 [vs] Skip MACsec clean up if /sbin/ip is not accessible
  vslib/src/MACsecManager.cpp
Labels: Enhancement

#751 [syncd][tests] Add syncd deprecated attribute value test
  syncd/SaiAttr.cpp
  tests/BCM56850.pl
  tests/BCM56850/depreacated.rec
  tests/BCM56850/non_depreacated.rec
Labels: Enhancement

#753 [meta] Fix stat_mode enums to sai_bulk_op_error_mode_t
  meta/Meta.cpp
Labels: Bug
