Repository sonic-net/sonic-sairedis, pull requests merged in 2021-03, with the labels that each got.

#791 [saiasiccmp] Add saiasiccmp tool to compare 2 asic views
  Makefile.am
  configure.ac
  debian/syncd.install
  saiasiccmp/AsicCmp.cpp
  saiasiccmp/AsicCmp.h
  saiasiccmp/CommandLineOptions.cpp
  saiasiccmp/CommandLineOptions.h
  saiasiccmp/CommandLineOptionsParser.cpp
  saiasiccmp/CommandLineOptionsParser.h
  saiasiccmp/Makefile.am
  saiasiccmp/SaiSwitchAsic.cpp
  saiasiccmp/SaiSwitchAsic.h
  saiasiccmp/View.cpp
  saiasiccmp/View.h
  saiasiccmp/ViewCmp.cpp
  saiasiccmp/ViewCmp.h
  saiasiccmp/dump1.json
  saiasiccmp/dump2.json
  saiasiccmp/dump3.json
  saiasiccmp/main.cpp
  saiasiccmp/test.sh
Labels: Enhancement

#807 [gbsyncd] Fix shebang in gbsyncd_startup.py; Make script executable
  syncd/scripts/gbsyncd_startup.py
Labels: Bug, Request for 202012 Branch

#808 Remove gbsyncd_start.sh
  syncd/scripts/gbsyncd_start.sh
Labels: Cleanup, Request for 202012 Branch

#809 Introduce gbsyncdmgrd; Deprecate gbsyncd_startup.py
  syncd/scripts/gbsyncd_startup.py
  syncd/scripts/gbsyncdmgrd
Labels: Enhancement, Request for 202012 Branch

#806 [pyext] Add SWIG sairedis python submodule
  Makefile.am
  configure.ac
  debian/control
  debian/python-pysairedis.dirs
  debian/python-pysairedis.install
  debian/python3-pysairedis.dirs
  debian/python3-pysairedis.install
  m4/python3.m4
  meta/sai_serialize.h
  pyext/Makefile.am
  pyext/fdb.h
  pyext/getapi.h
  pyext/lag.h
  pyext/nexthop.h
  pyext/py2/Makefile.am
  pyext/py2/__init__.py
  pyext/py3/Makefile.am
  pyext/py3/__init__.py
  pyext/pysairedis.cpp
  pyext/pysairedis.h
  pyext/pysairedis.i
  pyext/route.h
  pyext/routerinterface.h
  pyext/switch.h
  pyext/test.py
  pyext/vlan.h
  tests/aspell.en.pws
  tests/aspellcheck.pl
  tests/swsslogentercheck.pl
Labels: Enhancement

#811 [sairedis] Add sai_dbg_generate_dump api to redis interface
  lib/src/sai_redis_interfacequery.cpp
Labels: Enhancement
