Repository sonic-net/sonic-sairedis, pull requests merged in 2021-11, with the labels that each got.

#959 [syncd] Add workaround for warm boot new objects
  syncd/SaiSwitch.cpp
Labels: Enhancement

#960 [syncd] Add workaround for warm boot new objects
  syncd/SaiSwitch.cpp
Labels: Enhancement

#963 [az] Set diff coverage threshold to 50%
  .azure-pipelines/build-template.yml
Labels: Enhancement

#969 Fix hung issue when installing linux kernel modules
  .azure-pipelines/build_and_install_module.sh
Labels: Request for 202012 Branch, Request for 202106 Branch

#973 [lgtm] Add gmock libs to lgtm
  lgtm.yml
Labels: Enhancement

#968 Prevent other notification event storms to keep enqueue unchecked and drained all memory that leads to crashing the switch router
  syncd/NotificationQueue.cpp
  syncd/NotificationQueue.h
  unittest/syncd/Makefile.am
  unittest/syncd/TestNotificationQueue.cpp
Labels: Request for 201811 Branch :shipit:, Request for 201911 Branch, Request for 202012 Branch, Request for 202106 Branch
