Repository sonic-net/sonic-sairedis, pull requests merged in 2021-08, with the labels that each got.

#876 [vslib] Clean SwitchStateBase::send_fdb_event_notification
  vslib/src/SwitchStateBaseFdb.cpp
Labels: Cleanup

#880 [vslib] Clean Sai interface include
  vslib/inc/sai_vs.h
  vslib/src/sai_vs_fdb.cpp
  vslib/src/sai_vs_interfacequery.cpp
Labels: Cleanup, Enhancement

#882 Deprecate python module in favor to pyext
  Makefile.am
  configure.ac
  python/Makefile
  python/sairedis.cpp
  python/setup.py.in
  python/test.py
Labels: Cleanup, Enhancement

#879 [meta] [tests] Fix vlan set test
  meta/tests.cpp
Labels: Bug

#883 [sairedis] Add comment api to recorder
  lib/inc/Recorder.h
  lib/src/Recorder.cpp
  lib/src/RedisRemoteSaiInterface.cpp
Labels: Enhancement

#868 [syncd] Add event name to timer watchdog
  syncd/Makefile.am
  syncd/Syncd.cpp
  syncd/Syncd.h
  syncd/TimerWatchdog.cpp
  syncd/TimerWatchdog.h
  syncd/WatchdogScope.cpp
  syncd/WatchdogScope.h
Labels: Enhancement

#881 Add code coverage to configure.ac and Makefile.am
  .azure-pipelines/build-template.yml
  configure.ac
  lgtm.yml
  lib/src/Makefile.am
  meta/Makefile.am
  pyext/py2/Makefile.am
  pyext/py3/Makefile.am
  saiasiccmp/Makefile.am
  saidiscovery/Makefile.am
  saidump/Makefile.am
  saiplayer/Makefile.am
  saisdkdump/Makefile.am
  syncd/Makefile.am
  tests/Makefile.am
  vslib/src/Makefile.am
Labels: Enhancement, Cleanup

#884 [syncd] Add event data for timer watchdog to log entire event
  syncd/Syncd.cpp
  syncd/TimerWatchdog.cpp
  syncd/TimerWatchdog.h
  syncd/WatchdogScope.cpp
  syncd/WatchdogScope.h
Labels: Enhancement

#887 [meta] Simplify compilation for saimetadata.c
  meta/Makefile.am
Labels: Cleanup

#888 Move sairedis to c++14 standard
  configure.ac
  lib/src/Makefile.am
  saiplayer/Makefile.am
  syncd/Makefile.am
Labels: Enhancement, Cleanup

#889 [tests] Add vssyncd it's own main.cpp
  tests/Makefile.am
  tests/main.cpp
Labels: Enhancement, Cleanup

#890 [pyext] Add built sources list to makefiles
  pyext/py2/Makefile.am
  pyext/py3/Makefile.am
Labels: Enhancement, Cleanup

#858 [syncd][bcm] Start syncd by passing context configuration file
  syncd/scripts/syncd_init_common.sh
Labels: Chassis

#914 Code coverage enable html report directory
  .azure-pipelines/build-template.yml
  azure-pipelines.yml
Labels: Enhancement

#915 Remove gcovr htmlcov directory
  .azure-pipelines/build-template.yml
Labels: Cleanup
