Repository sonic-net/sonic-sairedis, pull requests merged in 2021-04, with the labels that each got.

#813 Remove gbsyncd_startup.py
  syncd/scripts/gbsyncd_startup.py
Labels: Cleanup, Request for 202012 Branch

#818 [meta] Mark local functions static
  meta/saiserialize.cpp
Labels: Cleanup

#822 Update .gitignore
  .gitignore
Labels: Cleanup

#821 [syncd] Bring back TimerWatchdog
  syncd/Syncd.cpp
Labels: Enhancement

#803 [Mellanox] Add SAI template config support
  syncd/scripts/syncd_init_common.sh
Labels: Request for 202012 Branch
