Repository sonic-net/sonic-sairedis, pull requests merged in 2021-09, with the labels that each got.

#878 Fix flex counters logic of converting poll interval to seconds from MS
  syncd/FlexCounter.cpp
Labels: Request for 202012 Branch, Request for 202106 Branch

#919 Add sairedis lib unit tests
  lib/ClientConfig.cpp
  lib/ServerConfig.cpp
  lib/client_config.json
  lib/context_config.json
  unittest/lib/Makefile.am
  unittest/lib/TestClientConfig.cpp
  unittest/lib/TestClientServerSai.cpp
  unittest/lib/TestContext.cpp
  unittest/lib/TestContextConfig.cpp
  unittest/lib/TestContextConfigContainer.cpp
  unittest/lib/TestSwitch.cpp
  unittest/lib/TestUtils.cpp
  unittest/lib/files/ccc_bad.txt
  unittest/lib/files/client_config_bad.txt
  unittest/lib/files/client_config_ok.txt
  unittest/vslib/TestBuffer.cpp
Labels: Enhancement

#906 [syncd] Comparison logic workaround for empty buffer profile
  syncd/AsicView.cpp
  syncd/AsicView.h
  syncd/ComparisonLogic.cpp
  syncd/ComparisonLogic.h
  syncd/SaiObj.cpp
  syncd/SaiObj.h
  tests/BCM56850.pl
  tests/BCM56850/buffer_profile_get_A.rec
  tests/BCM56850/buffer_profile_get_B.rec
  tests/BCM56850/full_ntf.rec
  tests/aspell.en.pws
Labels: Enhancement

#923 [vs] Fix return statment on hostif create
  vslib/SwitchStateBaseHostif.cpp
Labels: Bug

#922 Remove white space endings
  lib/Switch.cpp
  meta/Meta.h
  meta/SaiObject.cpp
  meta/sai_serialize.h
  syncd/scripts/syncd_init_common.sh
  tests/checkwhitespace.sh
  tests/findcrossinclude.sh
  unittest/lib/TestUtils.cpp
  unittest/lib/main.cpp
  unittest/lib/main_libsairedis.cpp
  unittest/lib/test_sai_redis_hostif.cpp
  unittest/meta/TestLegacy.cpp
  unittest/meta/TestNotificationFactory.cpp
  unittest/meta/TestNotificationFdbEvent.cpp
  unittest/meta/TestSaiSerialize.cpp
  unittest/meta/main.cpp
  unittest/syncd/Makefile.am
  unittest/vslib/TestFdbInfo.cpp
  unittest/vslib/TestSwitchBCM56850.cpp
  unittest/vslib/TestSwitchBCM81724.cpp
  unittest/vslib/TestSwitchMLNX2700.cpp
  unittest/vslib/TestTrafficForwarder.cpp
  unittest/vslib/main_libsaivs.cpp
  unittest/vslib/test_sai_vs_hostif.cpp
  vslib/Switch.cpp
Labels: Cleanup

#940 [unittest] Add NotificationBfdSessionStateChange tests
  unittest/meta/Makefile.am
  unittest/meta/TestNotificationBfdSessionStateChange.cpp
Labels: Enhancement

#930 [sairedis] Fail get/clear api on objects created in init view mode
  syncd/Syncd.cpp
  syncd/Syncd.h
Labels: Enhancement

#943 [unittest] Update meta tests
  meta/Meta.cpp
  meta/Meta.h
  unittest/meta/Makefile.am
  unittest/meta/MockMeta.cpp
  unittest/meta/MockMeta.h
  unittest/meta/TestMeta.cpp
Labels: Enhancement

#944 [syncd] Refactor syncd request shutdown command line parser
  syncd/RequestShutdownCommandLineOptionsParser.cpp
Labels: Enhancement

#945 [syncd] Fix SwitchNotifications to be const reference
  syncd/SwitchNotifications.cpp
  syncd/SwitchNotifications.h
Labels: Enhancement, Cleanup

#941 [syncd] Comparison logic workaround for empty buffer profile (#906)
  syncd/AsicView.cpp
  syncd/AsicView.h
  syncd/ComparisonLogic.cpp
  syncd/ComparisonLogic.h
  syncd/SaiObj.cpp
  syncd/SaiObj.h
  tests/BCM56850.pl
  tests/BCM56850/buffer_profile_get_A.rec
  tests/BCM56850/buffer_profile_get_B.rec
  tests/BCM56850/full_ntf.rec
  tests/aspell.en.pws
Labels: Enhancement
