Repository sonic-net/sonic-sairedis, pull requests merged in 2021-07, with the labels that each got.

#850 [sairedis] Style refactor
  lib/src/Recorder.cpp
  lib/src/tests.cpp
Labels: Cleanup

#848 [sairedis] Client/Server support SAI query API
  lib/inc/ServerSai.h
  lib/src/Makefile.am
  lib/src/ServerSai.cpp
  tests/testclient.cpp
Labels: Enhancement

#854 [syncd] bulk OID remove requires RID
  syncd/Syncd.cpp
Labels: Bug

#853 [sairedis] Client/Server support SAI fdb flush api
  lib/inc/ServerSai.h
  lib/src/ServerSai.cpp
  tests/testclient.cpp
Labels: Enhancement

#855 [sairedis] Client/Server add support for SAI stats api
  lib/inc/ServerSai.h
  lib/src/ServerSai.cpp
  tests/testclient.cpp
Labels: Enhancement

#847 [VS] Fix context config guid on RealObjectIdManager
  vslib/inc/VirtualSwitchSaiInterface.h
  vslib/src/Sai.cpp
  vslib/src/VirtualSwitchSaiInterface.cpp
Labels: Enhancement

#863 [syncd] Fix fdb flood queue size limit check
  syncd/NotificationProcessor.cpp
  syncd/NotificationQueue.cpp
Labels: Bug

#865 [meta] Allow objects with the same key exist on different switches
  meta/AttrKeyMap.cpp
  meta/AttrKeyMap.h
  meta/Meta.cpp
  meta/tests.cpp
  tests/BCM56850.pl
  tests/BCM56850/ctx_multi.json
  tests/BCM56850/lanemap_multi.ini
  tests/BCM56850/multi_switch_key.rec
  tests/BCM56850/vsprofile_ctx_multi.ini
  vslib/src/Sai.cpp
Labels: Bug

#864 [syncd] Clean up log messages and add performance timer for bulk route create
  syncd/Syncd.cpp
  syncd/TimerWatchdog.cpp
  syncd/VirtualOidTranslator.cpp
Labels: Cleanup, Enhancement

#874 [sairedis] Add context config fields conflict check
  lib/inc/ContextConfig.h
  lib/src/ContextConfig.cpp
  lib/src/ContextConfigContainer.cpp
Labels: Enhancement

#870 Update .gitignore
  .gitignore
Labels: Cleanup

#873 [meta] Use pragma once in serialize header
  meta/sai_serialize.h
Labels: Cleanup

#872 [sairedis] Fix thread run flag on close
  lib/src/ServerSai.cpp
Labels: Bug

#871 [tests] Fix error code check
  tests/BCM56850.pl
Labels: Bug

#867 [syncd] Fix status success on bulk fallback
  lib/src/RedisRemoteSaiInterface.cpp
  syncd/Syncd.cpp
Labels: Bug

#866 [syncd] Fix access coldvid table per switch
  syncd/RedisClient.cpp
Labels: Bug

#869 [sairedis] Record create, remove and set response in sync mode
  lib/inc/Recorder.h
  lib/src/Recorder.cpp
  lib/src/RedisRemoteSaiInterface.cpp
Labels: Enhancement
