Repository sonic-net/sonic-sairedis, pull requests merged in 2022-06, with the labels that each got.

#1052 [counter] Fix port flex counter
  syncd/FlexCounter.cpp
  syncd/FlexCounter.h
  unittest/syncd/MockableSaiInterface.cpp
  unittest/syncd/TestFlexCounter.cpp
Labels: Requested for 202205 branch

#1059 [vslib]: Fixbug in cleanup MACsec device
  unittest/vslib/TestMACsecManager.cpp
  vslib/MACsecManager.cpp
  vslib/MACsecManager.h
  vslib/SwitchStateBase.cpp
Labels: Requested for 202205 branch

#1065 [syncd] Support ACL action data object in remove dep tree
  syncd/ComparisonLogic.cpp
Labels: Enhancement

#1058 [sairedis] Perform log rotate on request
  lib/Recorder.cpp
  unittest/lib/Makefile.am
  unittest/lib/TestRecorder.cpp
Labels: Enhancement, Request for 202012 Branch
