Repository sonic-net/sonic-sairedis, pull requests merged in 2022-09, with the labels that each got.

#1107 [vslib]: Add SAI_PORT_ATTR_OPER_SPEED get
  unittest/vslib/TestSwitchBCM81724.cpp
  vslib/SwitchBCM81724.cpp
  vslib/SwitchStateBase.cpp
  vslib/SwitchStateBase.h
  vslib/SwitchStateBaseHostif.cpp
Labels: Request for 202205 branch

#1114 Create fabric ports for switch_type fabric.
  unittest/vslib/Makefile.am
  unittest/vslib/TestSwitchStateBase.cpp
  vslib/SwitchStateBase.cpp
Labels: Chassis

#1126 [lgtm] Add uuid library (#1119)
  lgtm.yml
Labels: Enhancement

#1123 [202205][vslib]: Add SAI_PORT_ATTR_OPER_SPEED get
  unittest/vslib/TestSwitchBCM81724.cpp
  vslib/SwitchBCM81724.cpp
  vslib/SwitchStateBase.cpp
  vslib/SwitchStateBase.h
  vslib/SwitchStateBaseHostif.cpp
Labels: Request for 202205 branch

#1061 Add Voqs to Virtual Switch
  tests/BCM56850.pl
  tests/BCM56850/voq_switch_create.rec
  unittest/vslib/TestSwitchStateBase.cpp
  vslib/SwitchStateBase.cpp
  vslib/SwitchStateBase.h
Labels: Chassis
