Repository sonic-net/sonic-sairedis, pull requests merged in 2022-07, with the labels that each got.

#1070 Support For CISCO debug-shell in syncd-container
  syncd/scripts/syncd_init_common.sh
Labels: Request for 202012 Branch, Request for 202205 branch

#1048 [syncd] Remove error message when tryTranslateVidToRid fails
  syncd/VirtualOidTranslator.cpp
  unittest/syncd/Makefile.am
  unittest/syncd/MockHelper.cpp
  unittest/syncd/TestFlexCounter.cpp
  unittest/syncd/TestVirtualOidTranslator.cpp
Labels: Cleanup

#1087 [sairedis] Fix reopen recoding file
  lib/Recorder.cpp
Labels: Bug, Cherry Pick Conflict_202012

#1075 Add SAI_OBJECT_TYPE_TUNNEL object to break-before-make list
  syncd/scripts/syncd_init_common.sh
Labels: Request for 202012 Branch, Request for 202205 branch
