Repository sonic-net/sonic-sairedis, pull requests merged in 2022-12, with the labels that each got.

#1153 enable cisco8000 SAI bulk API feature
  syncd/scripts/syncd_init_common.sh
Labels: Request for 202012 Branch, Request for 202205 branch

#1169 Initialize attr variables in Legacy.switch_get and LegacyFdbEntry.fdb_entry_get
  unittest/meta/TestLegacyFdbEntry.cpp
  unittest/meta/TestLegacyOther.cpp
Labels: Request for 202111 branch, Request for 202205 branch

#1127 Manage LANES mapping on VOQ system
  syncd/SaiSwitch.cpp
Labels: Chassis, Request for 202205 branch

#1162 * Add Voqs to Virtual Switch
  lgtm.yml
  tests/BCM56850.pl
  tests/BCM56850/voq_switch_create.rec
  unittest/vslib/Makefile.am
  unittest/vslib/TestSwitchStateBase.cpp
  vslib/SwitchStateBase.cpp
  vslib/SwitchStateBase.h
Labels: Chassis
