Repository sonic-net/sonic-sairedis, pull requests merged in 2023-10, with the labels that each got.

#1299 [vslib]: Fix method signatures
  vslib/SwitchMLNX2700.cpp
  vslib/SwitchStateBase.cpp
Labels: Bug, Enhancement

#1303 [syncd] Respect each api log level after sai discovery
  meta/SaiInterface.cpp
  meta/SaiInterface.h
  syncd/SaiDiscovery.cpp
  syncd/SaiDiscovery.h
  syncd/VendorSai.cpp
  syncd/VendorSai.h
Labels: Bug

#1308 The meta_sai_validate_fdb_entry() validates the input FDB entry for the set/remove operation. (#1154)
  meta/Meta.cpp
Labels: Bug

#1309 [syncd] Add pre match logic for pfc storm
  syncd/ComparisonLogic.cpp
  tests/BCM56850.pl
  tests/BCM56850/acl_pre_match_999.rec
Labels: Enhancement
