Repository sonic-net/sonic-sairedis, pull requests merged in 2023-07, with the labels that each got.

#1261 [CodeQL]: Fix syncd compilation in azp template
  .github/workflows/codeql-analysis.yml
Labels: Bug

#1260 [CI]: Fix collect log error in azp template
  .azure-pipelines/test-docker-sonic-vs-template.yml
Labels: Bug, Request for 202211 branch

#1264 [202211][CI]: Fix pipeline issue caused by urllib3 v2
  .azure-pipelines/test-docker-sonic-vs-template.yml
Labels: Bug

#1262 [CodeQL]: Use dependencies with relevant versions in azp template
  .github/workflows/codeql-analysis.yml
Labels: Bug

#1263 [202211][CodeQL]: Use dependencies with relevant versions in azp template
  .github/workflows/codeql-analysis.yml
Labels: Bug

#1266 [vs] Use boost join to concatenate switch types in config
  vslib/SwitchConfig.cpp
Labels: Enhancement
