Repository sonic-net/sonic-sairedis, pull requests merged in 2024-01, with the labels that each got.

#1337 [action] [PR:1302] [gbsyncd] Add asic db prefix for channel RESTARTQUERY (#1302)
  syncd/RequestShutdown.cpp
  syncd/RequestShutdown.h
  syncd/Syncd.cpp
Labels: automerge

#1338 Fix code coverage and ASAN not being enabled
  debian/rules
Labels: Request for 202311 Branch

#1339 Skip FABRIC PORT Attributes from sairedis logging (Issue 17583 )
  lib/SkipRecordAttrContainer.cpp
Labels: Request for 202205 Branch, Request for 202211 Branch, Request for 202305 Branch

#1341 Revert "add if statement for module control mode support"
  syncd/scripts/syncd_init_common.sh
Labels: Request for 202311 Branch
