Repository sonic-net/sonic-sairedis, pull requests merged in 2024-11, with the labels that each got.

#1437 Do not poll counters in bulk mode during initialization for objects that support bulk per CLI option
  syncd/CommandLineOptions.cpp
  syncd/CommandLineOptions.h
  syncd/CommandLineOptionsParser.cpp
  syncd/FlexCounter.cpp
  syncd/FlexCounter.h
  syncd/FlexCounterManager.cpp
  syncd/FlexCounterManager.h
  syncd/Syncd.cpp
  syncd/scripts/syncd_init_common.sh
  unittest/syncd/TestCommandLineOptions.cpp
  unittest/syncd/TestFlexCounter.cpp
Labels: Request for 202405 Branch

#1469 [meta] Use metadata to check port notification port_id type
  meta/Meta.cpp
  meta/Meta.h
  unittest/meta/TestMeta.cpp
Labels: Enhancement

#1470 [syncd] Add attribute version check feature
  syncd/AttrVersionChecker.cpp
  syncd/AttrVersionChecker.h
  syncd/CommandLineOptions.cpp
  syncd/CommandLineOptions.h
  syncd/CommandLineOptionsParser.cpp
  syncd/HardReiniter.cpp
  syncd/HardReiniter.h
  syncd/Makefile.am
  syncd/SaiDiscovery.cpp
  syncd/SaiDiscovery.h
  syncd/SaiSwitch.cpp
  syncd/SaiSwitch.h
  syncd/SingleReiniter.cpp
  syncd/SingleReiniter.h
  syncd/Syncd.cpp
  tests/aspell.en.pws
  tests/utils.pm
  unittest/syncd/Makefile.am
  unittest/syncd/TestAttrVersionChecker.cpp
  unittest/syncd/TestCommandLineOptions.cpp
Labels: Enhancement

#1472 [syncd] Introduce VendorSaiOptions class
  meta/SaiInterface.cpp
  meta/SaiInterface.h
  meta/SaiOptions.h
  syncd/HardReiniter.cpp
  syncd/HardReiniter.h
  syncd/SaiDiscovery.cpp
  syncd/SaiDiscovery.h
  syncd/SaiSwitch.cpp
  syncd/SaiSwitch.h
  syncd/SingleReiniter.cpp
  syncd/SingleReiniter.h
  syncd/Syncd.cpp
  syncd/VendorSaiOptions.h
  tests/aspell.en.pws
  unittest/meta/TestSaiInterface.cpp
Labels: Enhancement

#1401 Use temp view also in fast-reboot
  syncd/scripts/syncd_init_common.sh
Labels: Request for 202405 Branch

#1476 [action] [PR:1401] Use temp view also in fast-reboot (#1401)
  syncd/scripts/syncd_init_common.sh
Labels: automerge
