Repository sonic-net/sonic-sairedis, pull requests merged in 2024-02, with the labels that each got.

#1348 [action] [PR:1338] Fix code coverage and ASAN not being enabled (#1338)
  debian/rules
Labels: automerge

#1346 [action] [PR:1341] Revert "add if statement for module control mode support" (#1341)
  syncd/scripts/syncd_init_common.sh
Labels: automerge

#1354 [action] [PR:1339] Skip FABRIC PORT Attributes from sairedis logging (#1339)
  lib/SkipRecordAttrContainer.cpp
Labels: automerge

#1353 [action] [PR:1339] Skip FABRIC PORT Attributes from sairedis logging (#1339)
  lib/SkipRecordAttrContainer.cpp
Labels: automerge

#1355 Enable 8 Lanes Support in vslib
  vslib/LaneMapFileParser.cpp
Labels: Request for 202205 Branch, Request for 202305 Branch

#1352 Add new functionality to syncd_init_common.sh, to use common sai.profile
  syncd/scripts/syncd_init_common.sh
Labels: Enhancement, Request for 202311 Branch

#1359 [action] [PR:1352] Add new functionality to syncd_init_common.sh, to use common sai.profile (#1352)
  syncd/scripts/syncd_init_common.sh
Labels: automerge
