Repository sonic-net/sonic-sairedis, pull requests merged in 2024-10, with the labels that each got.

#1415 [202405][syncd] Enable bulk api for neighbor entries
  saiplayer/SaiPlayer.cpp
  syncd/Syncd.cpp
  syncd/tests.cpp
  syncd/tests/TestSyncdBrcm.cpp
  tests/BCM56850.pl
  tests/BCM56850/bulk_neighbor.rec
  unittest/lib/test_sai_redis_neighbor.cpp
  unittest/vslib/test_sai_vs_neighbor.cpp
Labels: Bug

#1412 [Mellanox] Resolve New Line Formatting Issues in syncd's sai.profile
  syncd/scripts/syncd_init_common.sh
Labels: Request for 202311 Branch, Request for 202405 Branch

#1420 [Marvell] Add Flag to identify SONiC related Init Handling
  syncd/scripts/syncd_init_common.sh
Labels: Request for 202311 Branch, Request for 202405 Branch

#1432 [syncd] Create neighbor entries before next hop
  syncd/ComparisonLogic.cpp
  tests/BCM56850.pl
  tests/BCM56850/neighbor_next_hop.rec
Labels: Enhancement

#1396 [fastboot] Notify SAI that fastboot is done
  configure.ac
  syncd/Syncd.cpp
  unittest/syncd/Makefile.am
  unittest/syncd/TestSyncd.cpp
Labels: Request for 202405 Branch

#1421 Fix adding flex counter to wrong context
  lib/RedisRemoteSaiInterface.cpp
  lib/RedisRemoteSaiInterface.h
  lib/Sai.cpp
  syncd/tests/TestSyncdMlnx.cpp
Labels: Request for 202405 Branch

#1427 [syncd] Make sure notification queue release memory when drained
  syncd/NotificationQueue.cpp
  syncd/NotificationQueue.h
  tests/aspell.en.pws
  unittest/syncd/TestNotificationQueue.cpp
Labels: Enhancement

#1434 [syncd] Fix inspect asic command
  syncd/Syncd.cpp
  tests/MLNX2700.pl
  tests/MLNX2700/inspect_asic.rec
  unittest/syncd/Makefile.am
  unittest/syncd/TestSyncd.cpp
  unittest/syncd/profile.ini
Labels: Enhancement

#1430 [syncd] Add workaround for port error status notification
  proxylib/Proxy.cpp
  proxylib/Proxy.h
  syncd/NotificationHandler.cpp
  syncd/NotificationHandler.h
  syncd/Syncd.cpp
  syncd/Workaround.cpp
  syncd/Workaround.h
  unittest/syncd/TestNotificationHandler.cpp
  unittest/syncd/TestWorkaround.cpp
Labels: Enhancement
