Repository sonic-net/sonic-sairedis, pull requests merged in 2025-04, with the labels that each got.

#1569 Fix invalid polling of port counters
  syncd/FlexCounter.cpp
Labels: Request for msft-202412 Branch

#1552 [ACL] Enable ACL multi-binding for Dual-ToR setups
  syncd/scripts/syncd_init_common.sh
Labels: Request for 202411 Branch

#1567 Move time stamp to time stamp table in counter database to avoid frequently update the counter table
  syncd/FlexCounter.cpp
  unittest/syncd/TestFlexCounter.cpp
Labels: Request for msft-202412 Branch

#1585 [action] [PR:1552] [ACL] Enable ACL multi-binding for Dual-ToR setups
  syncd/scripts/syncd_init_common.sh
Labels: automerge

#1576 [FlexCounter] add support for SRv6 MySID counters
  syncd/FlexCounter.cpp
  unittest/syncd/TestFlexCounter.cpp
Labels: Request for msft-202412 Branch

#1575 [trim]: Add Packet Trimming to VS lib
  unittest/vslib/TestSwitchStateBase.cpp
  vslib/SwitchStateBase.cpp
  vslib/SwitchStateBase.h
Labels: Request for msft-202412 Branch
