Repository sonic-net/sonic-sairedis, pull requests merged in 2025-02, with the labels that each got.

#1511 Use sonictest pool instead of sonic-common and fix arm64 issue.
  .azure-pipelines/test-docker-sonic-vs-template.yml
Labels: Request for 202411 Branch

#1517 [action] [PR:1496] [syncd] Support bulk set in INIT_VIEW mode
  syncd/Syncd.cpp
  syncd/tests/TestSyncdBrcm.cpp
Labels: automerge

#1416 [nvidia] Skip SAI discovery on ports
  syncd/Makefile.am
  syncd/SaiDiscovery.cpp
  syncd/Syncd.cpp
Labels: Request for 202411 Branch

#1505 [syncd] Move logSet logGet under mutex to prevent race condition
  syncd/VendorSai.cpp
  unittest/syncd/TestVendorSai.cpp
Labels: Bug, Cherry Pick Conflict_202405, Request for 202405 Branch, Request for 202411 Branch, Cherry Pick Conflict_202411

#1457 Optimize counter polling interval by making it more accurate
  lib/RedisRemoteSaiInterface.cpp
  syncd/FlexCounter.cpp
  syncd/FlexCounter.h
  tests/aspell.en.pws
  unittest/syncd/TestFlexCounter.cpp
Labels: Request for 202411 Branch, Cherry Pick Conflict_202411, Request for msft-202412 Branch, Cherry Pick Conflict_msft-202412

#1528 [action] [PR:1519] Define bulk chunk size and bulk chunk size per counter ID
  lib/sairedis.h
Labels: automerge

#1492 [syncd] Update log level for bulk api
  syncd/Syncd.cpp
  unittest/syncd/TestSyncd.cpp
Labels: Request for 202411 Branch, Cherry Pick Conflict_202411

#1533 [action] [PR:1484] [FC] Support Policer Counter
  meta/SaiSerialize.cpp
  meta/sai_serialize.h
  syncd/FlexCounter.cpp
  unittest/syncd/TestFlexCounter.cpp
Labels: automerge

#1535 [action] [PR:1514] Fix pipeline errors related to rsyslogd and libswsscommon installation
  .azure-pipelines/build-template.yml
  .azure-pipelines/test-docker-sonic-vs-template.yml
Labels: automerge

#1508 [hash] update ECMP/LAG hash VS lib with SAI_NATIVE_HASH_FIELD_IPV6_FLOW_LABEL
  syncd/tests/TestSyncdMlnx.cpp
  unittest/vslib/TestSwitchStateBase.cpp
  vslib/SwitchStateBase.cpp
Labels: Request for msft-202412 Branch

#1509 [sairedis/syncd] Implement bulk get support
  lib/ClientServerSai.cpp
  lib/Recorder.cpp
  lib/Recorder.h
  lib/RedisRemoteSaiInterface.cpp
  lib/RedisRemoteSaiInterface.h
  lib/Sai.cpp
  lib/ServerSai.cpp
  meta/Meta.cpp
  saiplayer/SaiPlayer.cpp
  saiplayer/SaiPlayer.h
  syncd/Syncd.cpp
  syncd/Syncd.h
  syncd/VendorSai.cpp
  syncd/tests/TestSyncdBrcm.cpp
  tests/BCM56850.pl
  tests/BCM56850/port_bulk_get.rec
  unittest/lib/TestClientServerSai.cpp
  unittest/lib/TestRedisRemoteSaiInterface.cpp
  unittest/lib/TestSai.cpp
  unittest/lib/TestServerSai.cpp
  unittest/meta/TestMeta.cpp
  unittest/syncd/TestVendorSai.cpp
  unittest/vslib/TestSai.cpp
  unittest/vslib/TestVirtualSwitchSaiInterface.cpp
  vslib/Sai.cpp
  vslib/SwitchStateBase.cpp
  vslib/SwitchStateBase.h
  vslib/VirtualSwitchSaiInterface.cpp
  vslib/VirtualSwitchSaiInterface.h
Labels: Request for msft-202412 Branch, Cherry Pick Conflict_msft-202412

#1541 [action] [PR:1498] Revert "Do not enter vendor SAI critical section for counter polling/clearing operations (#1450)"
  syncd/VendorSai.cpp
  unittest/syncd/TestVendorSai.cpp
Labels: automerge
